// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_native_bridge
// Run: dart run flutter_native_bridge:generate

import 'package:flutter/services.dart';

const _channel = MethodChannel('flutter_native_bridge');
const _eventChannelPrefix = 'flutter_native_bridge/events/';

/// Generated bridge for BuildService
class BuildService {
  BuildService._();

  /// Calls native BuildService.getBuildType
  static Future<String?> getBuildType() async {
    return _channel.invokeMethod<String>('BuildService.getBuildType');
  }
}

